dist: xenial
language: node_js
node_js:
  - "10"

# services:
# - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3
#   - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
#   - unzip ~/chromedriver_linux64.zip -d ~/
#   - rm ~/chromedriver_linux64.zip
#   - sudo mv -f ~/chromedriver /usr/local/share/
#   - sudo chmod +x /usr/local/share/chromedriver
#   - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - npm run coverage
  # - cd e2e-script && ./run-tests.sh

cache: npm

notifications:
  email: false